server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    url: ${mysql.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${mysql.secret}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update #update #create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 7MB

  security:
    user:
      name: test
      password: 1234

  cloud:
    aws:
      credentials:
        access-key: xxx
        secret-key: xxx
      s3:
        bucket: xxx
        url: xxx
      region:
        static: xxx

jwt:
  secret-key: ${jwt.secretkey}

oci:
  config:
    file-path: ${OCI_CONFIG_FILE_PATH}
    profile: ${OCI_CONFIG_PROFILE}
  objectstorage:
    namespace: ${OCI_OBJECTSTORAGE_NAMESPACE}
    bucket-name: ${OCI_OBJECTSTORAGE_BUCKET_NAME}
    region-id: ${OCI_OBJECTSTORAGE_REGION_ID}
